title: My first homepage
author: wrepi
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My first homepage! It will be an awesome page :)

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima #jekyll-theme-midnight
