title: My first page
author: wrepi
email: your-email@domain.com
description: > 
  My first blog! 
  It will be awesome :)

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
